name: "Terraform CI"

on:
  push:
    paths:
      - "**/*.tf"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.tf"
      - ".github/workflows/**"
  # This must be at the same level as push/pull_request
  workflow_dispatch:
    inputs:
      destroy:
        description: "Destroy Infrastructure?"
        type: boolean
        required: true
        default: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform-plan:
    name: "Terraform Validate & Plan"
    runs-on: ubuntu-latest
    # Skip planning if we are destroying
    if: github.event.inputs.destroy != 'true'

    env:
      AWS_REGION: "us-east-1"
      TF_LOG: INFO

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "AWS creds - OIDC"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::514005485562:role/GitHubActionsTerraformRole
          aws-region: ${{ env.AWS_REGION }}

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.0"

      - name: "Terraform init"
        id: init
        run: terraform init

      - name: "Terraform Plan"
        id: plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: "terraform plan upload"
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
          retention-days: 1

  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    # This job now runs even if 'terraform-plan' was skipped (due to destroy=true)
    needs: terraform-plan
    if: always() && (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch')
    environment: production

    env:
      AWS_REGION: "us-east-1"
      TF_LOG: INFO

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "AWS creds - OIDC"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::514005485562:role/GitHubActionsTerraformRole
          aws-region: ${{ env.AWS_REGION }}

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.0"

      - name: "Download Terraform Plan"
        if: github.event.inputs.destroy != 'true'
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: "Terraform init"
        id: init
        run: terraform init

      - name: "Terraform Apply or Destroy"
        run: |
          if [ "${{ github.event.inputs.destroy }}" = "true" ]; then
            echo "Destroying infrastructure..."
            terraform destroy -auto-approve -input=false
          else
            echo "Applying infrastructure..."
            terraform apply -input=false -no-color tfplan
          fi
